In [2]:
import numpy as np
import pandas as pd

In [5]:
A= np.arange(21,30).reshape(3,3)
A

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [6]:
np.linalg.inv(A)

LinAlgError: Singular matrix

In [7]:
arr1 = np.arange(5,21).reshape(4,4)

In [8]:
np.linalg.inv(arr1)

array([[ -6.77233027e+13,   6.09509724e+14,  -1.01584954e+15,
          4.74063119e+14],
       [ -3.26200575e+15,   3.83765382e+15,   2.11070960e+15,
         -2.68635767e+15],
       [  6.72718140e+15,  -9.50383681e+15,  -1.17387058e+15,
          3.95052599e+15],
       [ -3.39745235e+15,   5.05667327e+15,   7.90105198e+13,
         -1.73823144e+15]])

In [9]:
np.linalg.eig(arr1)

(array([  5.15518361e+01,  -1.55183609e+00,   2.79063957e-15,
          1.54032832e-15]),
 array([[-0.25245732,  0.71152323, -0.23612827, -0.04170769],
        [-0.39906523,  0.26598297,  0.68320002,  0.46267323],
        [-0.54567314, -0.17955729, -0.65801522, -0.80022337],
        [-0.69228106, -0.62509754,  0.21094347,  0.37925784]]))

In [7]:
arr1[1]

array([ 9, 10, 11, 12])

In [8]:
arr1

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [9]:
np.linalg.svd(arr1)

(array([[-0.24659338, -0.79949465,  0.53529746,  0.11600272],
        [-0.3962997 , -0.37808272, -0.80019327,  0.24431688],
        [-0.54600602,  0.04332921, -0.00550585, -0.83664191],
        [-0.69571235,  0.46474115,  0.27040165,  0.47632231]]),
 array([  5.32704861e+01,   1.50176966e+00,   5.10818522e-15,
          2.71923769e-16]),
 array([[-0.4453658 , -0.48074395, -0.5161221 , -0.55150026],
        [ 0.70827206,  0.26246   , -0.18335205, -0.6291641 ],
        [ 0.47842046, -0.83665939,  0.23805739,  0.12018154],
        [-0.26667182, -0.00103113,  0.80207773, -0.53437477]]))

In [10]:
u,s,v = np.linalg.svd(arr1)

In [11]:
u

array([[-0.24659338, -0.79949465,  0.53529746,  0.11600272],
       [-0.3962997 , -0.37808272, -0.80019327,  0.24431688],
       [-0.54600602,  0.04332921, -0.00550585, -0.83664191],
       [-0.69571235,  0.46474115,  0.27040165,  0.47632231]])

In [12]:
u.T

array([[-0.24659338, -0.3962997 , -0.54600602, -0.69571235],
       [-0.79949465, -0.37808272,  0.04332921,  0.46474115],
       [ 0.53529746, -0.80019327, -0.00550585,  0.27040165],
       [ 0.11600272,  0.24431688, -0.83664191,  0.47632231]])

In [13]:
u.T[0]

array([-0.24659338, -0.3962997 , -0.54600602, -0.69571235])

In [14]:
s[0] * np.outer(u.T[0], v[0])+s[1] * np.outer(u.T[1], v[1])

array([[  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.],
       [ 13.,  14.,  15.,  16.],
       [ 17.,  18.,  19.,  20.]])

In [15]:
np.outer(u.T[0], v[0])

array([[ 0.10982426,  0.11854828,  0.1272723 ,  0.13599632],
       [ 0.17649833,  0.19051869,  0.20453904,  0.21855939],
       [ 0.24317241,  0.26248909,  0.28180578,  0.30112246],
       [ 0.30984648,  0.3344595 ,  0.35907252,  0.38368554]])

In [22]:
np.diag(s)

array([[  5.32704861e+01,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   1.50176966e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   2.67585814e-15,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          2.33010163e-16]])

In [23]:
np.dot(u,np.diag(s))

array([[ -1.31361495e+01,  -1.20065682e+00,   1.46012275e-15,
          1.10513070e-17],
       [ -2.11110779e+01,  -5.67793161e-01,  -2.04142477e-15,
          8.00336174e-17],
       [ -2.90860064e+01,   6.50704971e-02,  -2.97518703e-16,
         -1.93221156e-16],
       [ -3.70609348e+01,   6.97934155e-01,   8.78820727e-16,
          1.02136231e-16]])

In [24]:
sprim=[s[0],0,0,0]

In [25]:
sprimdiag=np.diag(sprim)

In [26]:
sprimdiag

array([[ 53.27048609,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ]])

In [27]:
np.dot(u,sprimdiag)

array([[-13.13614948,   0.        ,   0.        ,   0.        ],
       [-21.11107792,   0.        ,   0.        ,   0.        ],
       [-29.08600636,   0.        ,   0.        ,   0.        ],
       [-37.0609348 ,   0.        ,   0.        ,   0.        ]])

In [29]:
np.dot(u,np.diag([1,0,0,0]))

array([[-0.24659338,  0.        ,  0.        ,  0.        ],
       [-0.3962997 ,  0.        ,  0.        ,  0.        ],
       [-0.54600602,  0.        ,  0.        ,  0.        ],
       [-0.69571235,  0.        ,  0.        ,  0.        ]])

In [30]:
s[0] * np.outer(u.T[0], v[0])

array([[  5.85039168,   6.31512439,   6.77985711,   7.24458983],
       [  9.40215203,  10.149023  ,  10.89589396,  11.64276493],
       [ 12.95391239,  13.9829216 ,  15.01193081,  16.04094002],
       [ 16.50567274,  17.8168202 ,  19.12796766,  20.43911511]])

In [31]:
s[0]

53.270486086347852

In [32]:
np.outer(u.T[0], v[0])

array([[ 0.10982426,  0.11854828,  0.1272723 ,  0.13599632],
       [ 0.17649833,  0.19051869,  0.20453904,  0.21855939],
       [ 0.24317241,  0.26248909,  0.28180578,  0.30112246],
       [ 0.30984648,  0.3344595 ,  0.35907252,  0.38368554]])

In [33]:
np.outer(u.T[0], v[0])*(1/0.10982426)

array([[ 0.99999999,  1.07943616,  1.15887234,  1.23830851],
       [ 1.60709786,  1.73475957,  1.86242127,  1.99008297],
       [ 2.21419574,  2.39008297,  2.5659702 ,  2.74185744],
       [ 2.82129361,  3.04540637,  3.26951913,  3.4936319 ]])

In [36]:
np.outer(u.T[0], v[0])*(1/0.17649833)

array([[ 0.62223965,  0.67166799,  0.72109632,  0.77052466],
       [ 1.00000002,  1.07943619,  1.15887237,  1.23830854],
       [ 1.37776039,  1.4872044 ,  1.59664841,  1.70609243],
       [ 1.75552076,  1.89497261,  2.03442446,  2.17387631]])

In [ ]:
np.outer(u.T[0], v[0])